### ISSUE TITLE
Sending commands actively

### ISSUE THREAD

**Issue by Alienmaster** [Otoru/jaspion#12]
**Is your feature request related to a problem? Please describe.**
Sending commands is like i understand only possible when a event occurs.
It would be nice if sending an command is independently possible. 
In my context i want to start a media bug later in the call not only when the caller enters the conference.
My only idea with jaspion (btw a great project!) is actual to wait for a heartbeat and send a command. But sending commands only with heartbeats would create a big delay.

**Comment by Otoru** [comment]
Hi, sorry for the delay in replying.

I like this idea, can you give me more details of your use case so we can think about an implementation?

**Comment by Alienmaster** [comment]
Hi! I use your project in a service to subtitle  Bigbluebutton. FS is part of BBB.

My actual implementation waits if somebody joins the conference and responses immediately to start another FS plugin to fork the audio. The in this implementation is that everybody starts this pipeline by joining the conference.

My idea is to send commands actively to FS without first getting some sort of event from the conference. In this case I could control who's audio is getting forked independent of their status (joining or already there).

I hope you get the idea. (And it isn't already total obviously possible and I overlooked it ;) )

My project: https://github.com/uhh-lt/bbb-live-subtitles

**Comment by Otoru** [comment]
I get your point, only with Jaspion it's really hard to do that.

I see two possibilities for evolution:

- Use the [greenswitch ](https://github.com/EvoluxBR/greenswitch)to actively send commands to the freeswitch.
- Use [genesis](https://github.com/Otoru/Genesis) to replace Jaspion and send commands actively to freeswitch.

The greenswitch is even used by jaspion under the hood to provide interaction with the freeswitch.

Genesis is another project of mine where I wrote everything from scratch to communicate with freeswitch to have more control over how things should happen.

Jaspion is intended to be just a friendlier interface for processing events.
